# Generated by Django 5.0.14 on 2026-04-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRenewalEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('expires_date_key', models.CharField(db_index=True, max_length=32)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscriptionrenewalemaillog',
            constraint=models.UniqueConstraint(fields=('user_id', 'expires_date_key'), name='uniq_renewal_email_user_expiry'),
        ),
    ]
