# Generated by Django 5.0.14 on 2026-04-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_subscription_renewal_email_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionRenewalEmailLog',
        ),
    ]
